slug: none

# Modality-specific augmentations, applied to specific modality independently
# Could be some noise, blur operations that does not introduce spatial changes.
individual:
  vv:
  vh:
  wind_direction:
  wind_speed:
  mask:

# Spatial transformations that are applied for image & boxes simultaneously
spatial:
