slug: balanced
sampler:
num_samples: 1024
crop_around_ship_p: 0.5

sampler_type: random_crop # {each_object, random_crop}

balance_crowd: True
balance_near_shore: True

balance_vessel_type: True
balance_fishing_type: True

balance_per_scene: False
balance_location: True