aggregation: weighted_sum
slug: rfl_soft_bce_smooth_l1_regularized_no_offset
losses_weights:
  losses/objectness: 1.0
  losses/vessel: 1.0
  losses/fishing: 1.0
  losses/size: 0.1
losses:
  - loss:
      _target_: xview3.centernet.losses.MultilabelCenterTrimmedLoss
      fraction: 0
      samplewise: False
      objectness_loss: rfl
      classifier_loss: soft_bce
      size_loss: smooth_l1
      offset_loss:
      regularization_weight: 0.5
      regularize_ignored: True
    prefix: ''
    target_key:
      - CENTERNET_TARGET_OBJECTNESS_MAP
      - CENTERNET_TARGET_VESSEL_MAP
      - CENTERNET_TARGET_FISHING_MAP
      - CENTERNET_TARGET_SIZE
    output_key:
      - CENTERNET_OUTPUT_OBJECTNESS_MAP
      - CENTERNET_OUTPUT_VESSEL_MAP
      - CENTERNET_OUTPUT_FISHING_MAP
      - CENTERNET_OUTPUT_SIZE
    weight: 1.0