slug: full_4fold
data_dir: ${oc.env:XVIEW3_DATA_DIR, "data"}

fold: 0
num_folds: 4

splitter: full

# If True, removes all objects with LOW confidence from training & validation.
filter_low_confidence_objects: False

# If True, sets IGNORE_LABEL on all labels (vessel, fishing, length) for that object.
ignore_low_confidence_labels: True

# If True, sets IGNORE_LABEL on all detection label for that object.
ignore_low_confidence_detections: True

# Define the number and order of channel in the input image
num_channels: 2
channels:
  - vh
  - vv


