__all__ = [
    "CENTERNET_OUTPUT_CLASS_MAP",
    "CENTERNET_OUTPUT_DECODED_PREDICTIONS",
    "CENTERNET_OUTPUT_FISHING_MAP",
    "CENTERNET_OUTPUT_OBJECTNESS_MAP",
    "CENTERNET_OUTPUT_OFFSET",
    "CENTERNET_OUTPUT_SIZE",
    "CENTERNET_OUTPUT_VESSEL_MAP",
    "CENTERNET_TARGET_CLASS_MAP",
    "CENTERNET_TARGET_FISHING_MAP",
    "CENTERNET_TARGET_OBJECTNESS_MAP",
    "CENTERNET_TARGET_OFFSET",
    "CENTERNET_TARGET_SIZE",
    "CENTERNET_TARGET_VESSEL_MAP",
]

CENTERNET_TARGET_CLASS_MAP = "CENTERNET_TARGET_CLASS_MAP"
CENTERNET_TARGET_FISHING_MAP = "CENTERNET_TARGET_FISHING_MAP"
CENTERNET_TARGET_OBJECTNESS_MAP = "CENTERNET_TARGET_OBJECTNESS_MAP"
CENTERNET_TARGET_OFFSET = "CENTERNET_TARGET_OFFSET"
CENTERNET_TARGET_SIZE = "CENTERNET_TARGET_SIZE"
CENTERNET_TARGET_VESSEL_MAP = "CENTERNET_TARGET_VESSEL_MAP"

CENTERNET_OUTPUT_CLASS_MAP = "CENTERNET_OUTPUT_CLASS_MAP"
CENTERNET_OUTPUT_FISHING_MAP = "CENTERNET_OUTPUT_FISHING_MAP"
CENTERNET_OUTPUT_OBJECTNESS_MAP = "CENTERNET_OUTPUT_OBJECTNESS_MAP"
CENTERNET_OUTPUT_OFFSET = "CENTERNET_OUTPUT_OFFSET"
CENTERNET_OUTPUT_SIZE = "CENTERNET_OUTPUT_SIZE"
CENTERNET_OUTPUT_VESSEL_MAP = "CENTERNET_OUTPUT_VESSEL_MAP"

CENTERNET_OUTPUT_DECODED_PREDICTIONS = "CENTERNET_OUTPUT_DECODED_PREDICTIONS"
